logging:
  level:
    org.springframework: ERROR
    com.oracle: DEBUG


spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  console.h2.enabled: true
  h2.console.path: /h2-console
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy